[build]
  publish = "build"
  functions = './functions/'
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
[[plugins]]
  package = "@netlify/plugin-functions-install-core"
[[redirects]]
from = "/static/*"
to = "/static/:splat"
status = 200